name: Update .nvmrc with latest Node.js LTS version

on:
  schedule:
    - cron: "0 11 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Get current Node.js version
        id: current_version
        run: echo "version=$(cat .nvmrc)" >> "$GITHUB_OUTPUT"

      - name: Set version in .nvmrc
        id: latest_version
        run: |
          version=$(curl -s https://nodejs.org/download/release/index.json | jq -r '[.[] | select(.lts != false)][0].version')
          echo "${version}" > .nvmrc
          echo "version=$(cat .nvmrc)" >> "$GITHUB_OUTPUT"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          base: main
          branch: update-node-lts-nvmrc
          delete-branch: true
          title: Update .nvmrc with latest Node.js LTS version
          commit-message: Update .nvmrc with latest Node.js LTS version
          body: |
            Updates `.nvmrc` from `${{ steps.current_version.outputs.version }}` to `${{ steps.latest_version.outputs.version }}`.
